import sqlite3
conn = sqlite3.connect('aizen.db')
cur = conn.cursor()
print('option_bars counts:')
cur.execute('SELECT COUNT(*) FROM option_bars'); print('  total:', cur.fetchone()[0])
cur.execute("SELECT underlying, COUNT(*) FROM option_bars GROUP BY underlying ORDER BY 2 DESC LIMIT 10")
for r in cur.fetchall(): print(' ', r)
print()
cur.execute('SELECT MAX(timestamp), MIN(timestamp) FROM option_bars')
print('range:', cur.fetchone())
print()
print('option_contracts counts:')
cur.execute('SELECT COUNT(*) FROM option_contracts'); print('  total:', cur.fetchone()[0])
cur.execute("SELECT underlying, COUNT(*) FROM option_contracts GROUP BY underlying ORDER BY 2 DESC LIMIT 10")
for r in cur.fetchall(): print(' ', r)
print()
print('underlying_bars counts:')
cur.execute('SELECT COUNT(*) FROM underlying_bars'); print('  total:', cur.fetchone()[0])
cur.execute("SELECT symbol, COUNT(*) FROM underlying_bars GROUP BY symbol ORDER BY 2 DESC LIMIT 10")
for r in cur.fetchall(): print(' ', r)
